version: '3'
services:
  mysql:
    image: mysql:5.7.32
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=abcde12345
      - MAX_CONNECTIONS=3000
      - TZ=Asia/Shanghai
    ports:
      - "10010:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-name-resolve --lower_case_table_names=1
